name: Test on Merge to Main
on:
  push:
    branches:
    - main
    - Task-1 # This is just since each task is on its own branch and not main
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # checkout the code 
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          pyhton-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings
